"""Tests for the seed loader.

Read the section headings before the assertions: they are what says which
claims are PROVEN and which are only CHECKED, because there is no Postgres
server in this environment and pretending otherwise would be worse than useless.

    ── generated, not written ──   pure Python: the columns come from the models
    ── the Postgres schema ──      PARSED and linted. Never executed. sqlglot
                                   reads the emitted DDL back and the tables it
                                   finds are compared with the tables the models
                                   imply — so "this SQL declares what I meant"
                                   is checked, and "this SQL runs on Postgres 16"
                                   is not.
    ── the schema, executed ──     the SAME generated schema, rendered for
                                   SQLite, actually run. The real corpus is
                                   loaded and read back; an UPDATE on the
                                   records table is refused by the database; a
                                   correction is appended; the CHECK constraints
                                   reject values the models would reject. Every
                                   claim in this block is executed.

What the SQLite block cannot prove: the Postgres spelling of anything in
`dialect.py` (JSONB, IDENTITY, TIMESTAMPTZ, plpgsql), the `BEFORE TRUNCATE`
trigger (SQLite has no TRUNCATE), and the REVOKE (SQLite has no privileges).
"""

from __future__ import annotations

import json
import sqlite3
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from pydantic import BaseModel

import seed
from openferment_core import schema as S
from seed.columns import Logical, columns_for_model, sql_column_name
from seed.registry import AUDIT, COLLECTIONS, SYNTHETIC

REPO = Path(__file__).resolve().parents[3]
FIXTURES = REPO / "fixtures" / "schema-instances.json"
CORPUS_DIR = REPO / "data" / "corpus"
SCHEMA_SQL = Path(seed.__file__).resolve().parent / "schema.sql"

#: `fixtures/schema-instances.json` holds every seeded entity verbatim, keyed by
#: the names Phase 1 used. `data/corpus/*.json` is the same corpus one file per
#: collection; it is generated by another part of this migration and may be
#: empty while that runs, so the tests that need real instances read the fixture
#: and the one test that needs the real directory copes with it being empty.
FIXTURE_KEYS = {
    "papers": "papers",
    "records": "records",
    "ontology": "ontology",
    "strains": "strains",
    "protocols": "protocols",
    "scenarios": "scenarios",
    "learn": "learnModules",
}


# ── fixtures ───────────────────────────────────────────────────────────


@pytest.fixture(scope="session")
def corpus_json() -> dict[str, list[dict[str, Any]]]:
    data: dict[str, list[dict[str, Any]]] = json.loads(FIXTURES.read_text("utf-8"))
    return data


@pytest.fixture(scope="session")
def corpus_dir(
    corpus_json: dict[str, list[dict[str, Any]]], tmp_path_factory: pytest.TempPathFactory
) -> Path:
    """The fixture corpus, written out as the seven files the loader reads."""
    out = tmp_path_factory.mktemp("corpus")
    for name, key in FIXTURE_KEYS.items():
        (out / f"{name}.json").write_text(json.dumps(corpus_json[key], ensure_ascii=False), "utf-8")
    return out


def _connect() -> sqlite3.Connection:
    connection = sqlite3.connect(":memory:")
    # SQLite fires BEFORE DELETE triggers for rows removed by REPLACE conflict
    # resolution ONLY when recursive_triggers is on, and it defaults off. Without
    # this line `INSERT OR REPLACE` rewrites a row of an append-only table in
    # place, silently — including a row of audit_event, so the rewrite leaves no
    # trace. Postgres has no REPLACE, so this is not a hole in the shipped
    # schema; it is a hole in the EVIDENCE, and the evidence is the whole reason
    # the SQLite rendering exists.
    connection.execute("PRAGMA foreign_keys = ON")
    connection.execute("PRAGMA recursive_triggers = ON")
    connection.executescript(seed.schema_sql(seed.SQLITE))
    return connection


@pytest.fixture
def db() -> Iterator[sqlite3.Connection]:
    connection = _connect()
    try:
        yield connection
    finally:
        connection.close()


@pytest.fixture
def loaded(db: sqlite3.Connection, corpus_dir: Path) -> sqlite3.Connection:
    corpus = seed.read_corpus(corpus_dir)
    seed.load(db.cursor(), corpus, seed.SQLITE)
    return db


def _dumped(model: type[BaseModel], raw: dict[str, Any]) -> dict[str, Any]:
    """A corpus entry as the model re-emits it — the only fair comparison.

    The corpus writes `"value": 15` where the model's `float | str` makes it
    15.0, so comparing a row round trip against the raw JSON would report a
    difference that is not one. Both sides go through the model; what is being
    tested is what the database did in between.
    """
    return model.model_validate(raw).model_dump(mode="json", by_alias=True, exclude_none=True)


# ── generated, not written ─────────────────────────────────────────────


def test_every_model_field_becomes_a_column_or_is_declared_external() -> None:
    """The guarantee the whole generator exists for.

    A field added to a model cannot be forgotten in the DDL, because the DDL
    does not have a list of fields to forget it from.
    """
    for table in seed.tables():
        assert table.model is not None
        covered = {c.field for c in table.columns if c.field is not None}
        for name in table.model.model_fields:
            assert name in covered or name in table.externalised, (
                f"{table.model.__name__}.{name} has no column in {table.name} and is not "
                f"declared as externalised. Regenerate, or declare it."
            )


def test_every_column_is_derived_or_carries_its_reason() -> None:
    """A hand-written column with no stated reason cannot survive review."""
    for table in seed.tables():
        for column in table.columns:
            if column.derived:
                continue
            assert column.why, f"{table.name}.{column.name} is synthetic and says nothing"
            assert column.name in {c.name for c in SYNTHETIC.get(table.name, ())}


def test_the_only_externalised_field_is_the_audit_trail() -> None:
    external = {(t.name, field) for t in seed.tables() for field in t.externalised}
    assert external == {(AUDIT.parent, AUDIT.field)}


@pytest.mark.parametrize(
    ("table_name", "column_name", "logical", "nullable"),
    [
        ("papers", "year", Logical.BIGINT, False),  # a sentinel of 0 is still an int
        ("papers", "authors", Logical.JSON, False),
        ("papers", "doi", Logical.TEXT, True),
        ("papers", "open_access", Logical.BOOLEAN, False),
        ("papers", "tranche", Logical.SMALLINT, False),
        ("papers", "coverage_disputed", Logical.JSON, True),
        ("records", "confidence", Logical.DOUBLE, False),
        ("records", "value_num", Logical.DOUBLE, True),
        ("records", "value_txt", Logical.TEXT, True),
        ("records", "is_primary", Logical.BOOLEAN, False),
        ("records", "si", Logical.JSON, False),
        ("records", "method", Logical.TEXT, True),
        ("ontology", "range", Logical.JSON, False),
        ("strains", "bsl", Logical.SMALLINT, False),
        ("scenarios", "point", Logical.JSON, False),
        ("learn_modules", "index", Logical.BIGINT, False),
        ("audit_event", "from", Logical.JSON, True),
        ("audit_event", "to", Logical.JSON, True),
    ],
)
def test_type_mapping(table_name: str, column_name: str, logical: Logical, nullable: bool) -> None:
    column = seed.table_by_name(table_name).by_name(column_name)
    assert column.logical is logical
    assert column.nullable is nullable


def test_a_new_model_field_appears_in_the_ddl() -> None:
    """The claim "a field cannot be forgotten" is only worth as much as this.

    A model that does not exist anywhere in the schema is given a field, and the
    derivation is asked what columns it implies. Nothing about this test knows
    the field's name in advance.
    """

    class Invented(S.ExtractionRecord):
        newly_added_field: str | None = None

    names = {c.name for c in columns_for_model(Invented)}
    assert "newly_added_field" in names
    column = next(c for c in columns_for_model(Invented) if c.name == "newly_added_field")
    assert column.logical is Logical.TEXT
    assert column.nullable is True


def test_a_scalar_union_splits_into_one_column_per_arm() -> None:
    """`float | str` is not special-cased; any scalar union splits."""

    class Invented(BaseModel):
        measurement: int | str

    columns = columns_for_model(Invented)
    assert {(c.name, c.logical) for c in columns} == {
        ("measurement_int", Logical.BIGINT),
        ("measurement_txt", Logical.TEXT),
    }


def test_python_keyword_escape_is_undone_for_sql() -> None:
    assert sql_column_name("from_") == "from"
    assert sql_column_name("to") == "to"
    # A trailing underscore that is NOT a keyword escape is left alone.
    assert sql_column_name("value_") == "value_"


def test_schema_sql_is_up_to_date() -> None:
    """The checked-in DDL is the models' output, not a copy of it that drifted."""
    assert SCHEMA_SQL.exists()
    assert SCHEMA_SQL.read_text("utf-8") == seed.schema_sql(seed.POSTGRES), (
        "seed/schema.sql no longer matches the Pydantic models. Run "
        "`python3 packages/core/seed/cli.py emit` — do not edit the SQL."
    )


@pytest.mark.parametrize(
    ("table_name", "column_name", "member"),
    [
        ("records", "provenance", "industry-estimate"),
        ("records", "provenance", "curated"),
        ("records", "method", "undetermined"),
        ("records", "method", "urea-PAGE + phosphatase"),
        ("records", "evidence_class", "literature"),
        ("papers", "ingest", "stage:extract"),
        ("papers", "source_type", "industry-report"),
        ("ontology", "id", "minimum_selling_price"),
    ],
)
def test_enum_members_reach_the_check_constraint(
    table_name: str, column_name: str, member: str
) -> None:
    """Invariant 3 and 4 in the database: the values with punctuation in them,
    the sentinel, and the provenance classes an aggregate must exclude."""
    column = seed.table_by_name(table_name).by_name(column_name)
    assert column.allowed is not None
    assert member in column.allowed


# ── the Postgres schema: linted as text ────────────────────────────────
#
# The statements are also read back with a real SQL parser, which needs sqlglot
# and therefore lives in `test_seed_ddl.py` — a separate module so that a
# missing parser skips those five tests and not this whole file.


def test_reserved_words_are_quoted() -> None:
    """`from` and `to` are columns. Unquoted, the audit table would not parse.

    `test_seed_ddl.py` would already have failed to parse the audit table, so
    this one is about saying out loud which identifiers that depends on.
    """
    sql = seed.schema_sql(seed.POSTGRES)
    assert '"from" JSONB' in sql
    assert '"to" JSONB' in sql
    for table in seed.tables():
        for column in table.columns:
            assert f'"{column.name}"' in sql


def test_append_only_tables_carry_both_triggers_and_the_revoke() -> None:
    sql = seed.schema_sql(seed.POSTGRES)
    append_only = [t.name for t in seed.tables() if t.append_only]
    assert set(append_only) == {"records", "audit_event"}
    for name in append_only:
        assert f'BEFORE UPDATE OR DELETE ON "{name}"' in sql
        # TRUNCATE fires no row-level trigger; without this it is a way out.
        assert f'BEFORE TRUNCATE ON "{name}"' in sql
        assert f'REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "{name}" FROM PUBLIC' in sql


def test_nothing_else_is_append_only_by_accident() -> None:
    """An upsert exists for every table that is not append-only, and for none
    that is — the two lists are the same list, read twice."""
    for table in seed.tables():
        if table.append_only:
            with pytest.raises(ValueError):
                seed.rows.upsert_sql(table, seed.POSTGRES)
        else:
            assert "ON CONFLICT" in seed.rows.upsert_sql(table, seed.POSTGRES)


def test_comments_carry_the_field_descriptions_into_the_database() -> None:
    """Invariant 5: the docstrings port with the types, all the way down."""
    sql = seed.schema_sql(seed.POSTGRES)
    assert 'COMMENT ON COLUMN "papers"."year"' in sql
    assert "0 where the year is genuinely unknown" in sql
    assert "Surrogate key" in sql  # records.row_id says why it is not derived


# ── the schema, executed (SQLite) ──────────────────────────────────────


def test_the_generated_schema_creates(db: sqlite3.Connection) -> None:
    names = {
        row[0]
        for row in db.execute("SELECT name FROM sqlite_master WHERE type IN ('table','view')")
    }
    for table in seed.tables():
        assert table.name in names
    assert "records_current" in names


def test_the_whole_corpus_loads(loaded: sqlite3.Connection, corpus_dir: Path) -> None:
    counts = seed.read_corpus(corpus_dir).counts()
    for collection in COLLECTIONS:
        rows = loaded.execute(f'SELECT count(*) FROM "{collection.table}"').fetchone()[0]
        assert rows == counts[collection.name], collection.name


@pytest.mark.parametrize("name", sorted(FIXTURE_KEYS))
def test_every_entity_round_trips_through_the_database(
    loaded: sqlite3.Connection, corpus_json: dict[str, list[dict[str, Any]]], name: str
) -> None:
    """The acceptance test. Real literature in, the same literature out.

    Not a shape check: every field of every one of the 315 seeded entities is
    compared, including the ones that only appear a handful of times.
    """
    model = next(c.model for c in COLLECTIONS if c.name == name)
    want = [_dumped(model, raw) for raw in corpus_json[FIXTURE_KEYS[name]]]
    got = seed.read_collection(loaded.cursor(), seed.SQLITE, name)
    assert got == want


def test_a_categorical_record_keeps_its_string(loaded: sqlite3.Connection) -> None:
    """`ExtractionRecord.value` is `float | str` because these exist."""
    rows = loaded.execute(
        'SELECT count(*) FROM "records" WHERE "value_txt" IS NOT NULL'
    ).fetchone()[0]
    assert rows > 0
    mixed = loaded.execute(
        'SELECT count(*) FROM "records" WHERE "value_txt" IS NOT NULL AND "value_num" IS NOT NULL'
    ).fetchone()[0]
    assert mixed == 0


def test_numeric_records_are_numbers_in_the_database(loaded: sqlite3.Connection) -> None:
    """The reason for two columns rather than one JSON one: this works."""
    average = loaded.execute(
        'SELECT avg("value_num") FROM "records" WHERE "field" = \'titer_secreted\''
    ).fetchone()[0]
    assert average is None or isinstance(average, float)


def test_the_year_sentinel_survives(loaded: sqlite3.Connection) -> None:
    """Invariant 4: `year: 0` means unknown and is not a value to be tidied."""
    zeros = loaded.execute('SELECT count(*) FROM "papers" WHERE "year" = 0').fetchone()[0]
    assert zeros > 0
    papers = seed.read_collection(loaded.cursor(), seed.SQLITE, "papers")
    assert any(p["year"] == 0 for p in papers)


def test_the_unstated_venue_survives(
    loaded: sqlite3.Connection, corpus_json: dict[str, list[dict[str, Any]]]
) -> None:
    """Whatever string the corpus uses for an unstated venue comes back as it
    went in — including that it is a string and not a NULL."""
    venues = {p["venue"] for p in corpus_json["papers"]}
    back = {p["venue"] for p in seed.read_collection(loaded.cursor(), seed.SQLITE, "papers")}
    assert back == venues


def test_undetermined_survives_as_a_method(loaded: sqlite3.Connection) -> None:
    """Absence of measurement is not measurement of absence (OF-COR-001 §17)."""
    count = loaded.execute(
        'SELECT count(*) FROM "records" WHERE "method" = \'undetermined\''
    ).fetchone()[0]
    assert count > 0


# ── append-only, executed ──────────────────────────────────────────────


def _one_record(**over: Any) -> S.ExtractionRecord:
    base: dict[str, Any] = {
        "id": "r-seed-1",
        "paperId": "H4",
        "sectionId": "s1",
        "quote": "a quoted span",
        "field": "titer_secreted",
        "value": 1.0,
        "unit": "g L⁻¹",
        "si": {"value": 1.0, "unit": "kg m⁻³"},
        "confidence": 0.9,
        "status": "unverified",
        "provenance": "curated",
        "audit": [{"at": "2026-08-10 09:00", "who": "S. Creighton", "action": "curated"}],
        "isPrimary": True,
        "evidenceClass": "literature",
    }
    base.update(over)
    return S.ExtractionRecord.model_validate(base)


def _insert(db: sqlite3.Connection, record: S.ExtractionRecord) -> int:
    cursor = db.cursor()
    corpus = seed.LoadedCorpus(items={"records": [record]})
    seed.load(cursor, corpus, seed.SQLITE)
    return int(db.execute('SELECT max("row_id") FROM "records"').fetchone()[0])


def test_update_on_records_is_refused_by_the_database(db: sqlite3.Connection) -> None:
    _insert(db, _one_record())
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        db.execute('UPDATE "records" SET "unit" = \'mg/L\'')


def test_delete_on_records_is_refused_by_the_database(db: sqlite3.Connection) -> None:
    _insert(db, _one_record())
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        db.execute('DELETE FROM "records" WHERE "id" = \'r-seed-1\'')


def test_deleting_every_row_is_refused_too(db: sqlite3.Connection) -> None:
    """`DELETE FROM records` with no WHERE is the whole table in one statement.

    SQLite's truncate optimisation would skip row triggers; having a DELETE
    trigger disables it. Postgres has the same hole under a different name and
    the emitted schema plugs it with a BEFORE TRUNCATE trigger, which SQLite
    cannot test because it has no TRUNCATE.
    """
    _insert(db, _one_record())
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        db.execute('DELETE FROM "records"')


def test_the_audit_trail_is_append_only_as_well(db: sqlite3.Connection) -> None:
    """An editable audit trail on an uneditable table is not an audit trail."""
    _insert(db, _one_record())
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        db.execute('UPDATE "audit_event" SET "who" = \'somebody else\'')
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        db.execute('DELETE FROM "audit_event"')


def test_a_correction_is_a_new_row_that_supersedes_the_old_one(db: sqlite3.Connection) -> None:
    original = _insert(db, _one_record())
    corrected = _one_record(
        value=2.5,
        status="verified",
        corrected={"value": 2.5, "unit": "g L⁻¹"},
        reviewer="A. Reviewer",
        audit=[
            {"at": "2026-08-10 09:00", "who": "S. Creighton", "action": "curated"},
            {
                "at": "2026-08-11 11:00",
                "who": "A. Reviewer",
                "action": "corrected",
                "from": 1.0,
                "to": 2.5,
            },
        ],
    )
    new_row = seed.append_correction(db.cursor(), corrected, seed.SQLITE, supersedes=original)

    assert new_row != original
    # The superseded row is still there, exactly as it was written.
    kept = db.execute(
        'SELECT "value_num", "status" FROM "records" WHERE "row_id" = ?', [original]
    ).fetchone()
    assert kept == (1.0, "unverified")

    current = seed.read_collection(db.cursor(), seed.SQLITE, "records")
    assert len(current) == 1
    assert current[0]["value"] == 2.5
    assert current[0]["audit"][1]["from"] == 1.0
    assert current[0]["audit"][1]["to"] == 2.5


def test_a_correction_chain_cannot_fork(db: sqlite3.Connection) -> None:
    """Two rows superseding the same row would leave `records_current`
    ambiguous, so `supersedes` is UNIQUE."""
    original = _insert(db, _one_record())
    seed.append_correction(db.cursor(), _one_record(value=2.0), seed.SQLITE, supersedes=original)
    with pytest.raises(sqlite3.IntegrityError):
        seed.append_correction(
            db.cursor(), _one_record(value=3.0), seed.SQLITE, supersedes=original
        )


def test_loading_twice_into_the_records_table_is_refused(
    db: sqlite3.Connection, corpus_dir: Path
) -> None:
    corpus = seed.read_corpus(corpus_dir)
    cursor = db.cursor()
    seed.load(cursor, corpus, seed.SQLITE)
    with pytest.raises(RuntimeError, match="append-only"):
        seed.load(cursor, corpus, seed.SQLITE)


def test_reference_tables_converge_on_a_reload(db: sqlite3.Connection, corpus_dir: Path) -> None:
    """Papers, ontology, strains, protocols, scenarios and learn modules are a
    projection of the JSON, so re-running the loader must not duplicate them."""
    corpus = seed.read_corpus(corpus_dir)
    cursor = db.cursor()
    seed.load(cursor, corpus, seed.SQLITE)
    before = db.execute('SELECT count(*) FROM "papers"').fetchone()[0]
    seed.load(cursor, corpus, seed.SQLITE, append=True)
    assert db.execute('SELECT count(*) FROM "papers"').fetchone()[0] == before


# ── the constraints, executed ──────────────────────────────────────────


def test_the_database_refuses_a_provenance_the_model_would_refuse(
    db: sqlite3.Connection,
) -> None:
    """`extra='forbid'` and a CHECK constraint are the same policy, twice —
    once where the corpus is parsed and once where it is stored."""
    with pytest.raises(sqlite3.IntegrityError):
        db.execute(
            'INSERT INTO "records" ("id","paper_id","section_id","quote","field","value_num",'
            '"unit","si","confidence","status","provenance","is_primary","evidence_class") '
            "VALUES ('x','H4','s1','q','titer_secreted',1.0,'g/L','{}',0.9,'unverified',"
            "'probably-fine',1,'literature')"
        )


def test_a_record_must_be_on_exactly_one_arm(db: sqlite3.Connection) -> None:
    columns = (
        '"id","paper_id","section_id","quote","field","unit","si","confidence","status",'
        '"provenance","is_primary","evidence_class"'
    )
    tail = "'H4','s1','q','titer_secreted','g/L','{}',0.9,'unverified','curated',1,'literature'"
    with pytest.raises(sqlite3.IntegrityError):  # neither arm
        db.execute(f"INSERT INTO \"records\" ({columns}) VALUES ('a',{tail})")
    with pytest.raises(sqlite3.IntegrityError):  # both arms
        db.execute(
            f'INSERT INTO "records" ({columns},"value_num","value_txt") '
            f"VALUES ('b',{tail},1.0,'also this')"
        )


def test_an_audit_event_must_belong_to_a_record(db: sqlite3.Connection) -> None:
    with pytest.raises(sqlite3.IntegrityError):
        db.execute(
            'INSERT INTO "audit_event" ("record_row_id","ordinal","at","who","action") '
            "VALUES (9999, 0, 'now', 'nobody', 'invented')"
        )


def test_a_range_is_a_pair(db: sqlite3.Connection) -> None:
    """`ParameterDef.range` is `tuple[float, float]`; the arity check ports."""
    with pytest.raises(sqlite3.IntegrityError):
        db.execute(
            'INSERT INTO "ontology" ("id","family","name","definition","canonical_unit",'
            "\"range\",\"notes\") VALUES ('titer_secreted','expression','n','d','g/L',"
            "'[1, 2, 3]','')"
        )


def test_the_audit_trail_keeps_its_order(db: sqlite3.Connection) -> None:
    """A JSON array is ordered; SQL rows are not. `ordinal` is the difference."""
    record = _one_record(
        audit=[
            {"at": "2026-08-10 09:00", "who": "one", "action": "first"},
            {"at": "2026-08-10 10:00", "who": "two", "action": "second"},
            {"at": "2026-08-10 11:00", "who": "three", "action": "third"},
        ]
    )
    _insert(db, record)
    back = seed.read_collection(db.cursor(), seed.SQLITE, "records")[0]
    assert [event["who"] for event in back["audit"]] == ["one", "two", "three"]


def test_audit_from_and_to_round_trip_whatever_they_hold(db: sqlite3.Connection) -> None:
    """`AuditEvent.from` is `Any` because a correction can be of any shape.

    The seeded corpus never populates it — every one of its 134 audit events is
    a curation note with no from/to — so this is the only place the two columns
    are exercised, and it exercises them with the three shapes the TypeScript's
    `unknown` allows.
    """
    record = _one_record(
        audit=[
            {"at": "t", "who": "w", "action": "number", "from": 1.5, "to": 2.5},
            {"at": "t", "who": "w", "action": "string", "from": "unverified", "to": "verified"},
            {
                "at": "t",
                "who": "w",
                "action": "object",
                "from": {"value": 1.0, "unit": "g/L"},
                "to": {"value": 1000.0, "unit": "mg/L"},
            },
        ]
    )
    _insert(db, record)
    stored = db.execute('SELECT "from", "to" FROM "audit_event" ORDER BY "ordinal"').fetchall()
    assert stored[0] == ("1.5", "2.5")  # JSON text, not a SQL number

    back = seed.read_collection(db.cursor(), seed.SQLITE, "records")[0]["audit"]
    assert back[0]["from"] == 1.5
    assert back[1]["to"] == "verified"
    assert back[2]["from"] == {"value": 1.0, "unit": "g/L"}


# ── the repository's own corpus directory ──────────────────────────────


def test_the_repo_corpus_directory_loads_and_comes_back_unchanged(
    db: sqlite3.Connection,
) -> None:
    """The files the loader is actually pointed at, not a fixture copy of them.

    `data/corpus/*.json` is written by another part of this migration and may be
    empty while that runs, so this asserts a relationship rather than a number:
    every entity in each file becomes a row, and every row comes back as the
    entity that went in. It holds when the files are empty and starts meaning
    something the moment they are filled, without being edited.

    A failure here is one of two things, and the message says which: the corpus
    grew a shape the models reject (in which case the MODEL is wrong — see
    `scripts/validate_fixtures.py`), or this loader lost something in between.
    """
    corpus = seed.read_corpus(CORPUS_DIR)
    cursor = db.cursor()
    seed.load(cursor, corpus, seed.SQLITE)

    for collection in COLLECTIONS:
        raw = json.loads((CORPUS_DIR / f"{collection.name}.json").read_text("utf-8"))
        rows = db.execute(f'SELECT count(*) FROM "{collection.table}"').fetchone()[0]
        assert rows == len(raw), (
            f"{collection.name}: {len(raw)} entities in the file, {rows} rows in the table"
        )
        want = [_dumped(collection.model, entry) for entry in raw]
        got = seed.read_collection(cursor, seed.SQLITE, collection.name)
        assert got == want, f"{collection.name} did not survive the round trip"


def test_a_missing_corpus_file_is_an_error_and_lists_itself(tmp_path: Path) -> None:
    (tmp_path / "papers.json").write_text("[]", "utf-8")
    with pytest.raises(seed.CorpusError) as caught:
        seed.read_corpus(tmp_path)
    assert len(caught.value.failures) == len(COLLECTIONS) - 1


def test_a_corpus_entity_that_does_not_parse_names_itself(tmp_path: Path) -> None:
    """Where a real corpus instance fails, the MODEL is wrong — and the failure
    has to say which entity and which field, or the fix is guesswork."""
    for collection in COLLECTIONS:
        (tmp_path / f"{collection.name}.json").write_text("[]", "utf-8")
    (tmp_path / "records.json").write_text(
        json.dumps([{"id": "r-broken", "paperId": "H4"}]), "utf-8"
    )
    with pytest.raises(seed.CorpusError) as caught:
        seed.read_corpus(tmp_path)
    assert any("records/r-broken" in failure for failure in caught.value.failures)


def _quoted(columns: list[str]) -> str:
    """`audit_event` really has columns named `from` and `to` (AuditEvent's own
    field names). The DDL quotes them; anything hand-writing SQL against these
    tables has to as well."""
    return ", ".join(f'"{c}"' for c in columns)


def test_insert_or_replace_cannot_rewrite_an_append_only_row(loaded: sqlite3.Connection) -> None:
    """The hole this closes was in the evidence, not in the shipped schema.

    SQLite fires BEFORE DELETE triggers for rows removed by REPLACE conflict
    resolution only when `recursive_triggers` is on, and it defaults OFF. With
    the default, `INSERT OR REPLACE` rewrote a row of `records` in place and the
    append-only trigger never fired — so the suite was claiming a proof that
    rows cannot be rewritten while executing a rendering in which they could.

    Postgres has no REPLACE and was never exposed. But the SQLite rendering
    exists precisely to execute what the DDL says, and it has to execute all of
    it or it is decoration.
    """
    columns = [d[0] for d in loaded.execute("SELECT * FROM records LIMIT 1").description]
    row = list(loaded.execute("SELECT * FROM records WHERE row_id = 1").fetchone())
    row[columns.index("id")] = "FORGED"
    placeholders = ", ".join("?" * len(columns))
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        loaded.execute(
            f"INSERT OR REPLACE INTO records ({_quoted(columns)}) VALUES ({placeholders})", row
        )
    assert loaded.execute("SELECT id FROM records WHERE row_id = 1").fetchone()[0] != "FORGED"


def test_insert_or_replace_cannot_rewrite_the_audit_trail(loaded: sqlite3.Connection) -> None:
    """The worse half: an audit row rewritten leaves no trace that it was."""
    columns = [d[0] for d in loaded.execute("SELECT * FROM audit_event LIMIT 1").description]
    first = loaded.execute("SELECT * FROM audit_event LIMIT 1").fetchone()
    if first is None:
        pytest.skip("no audit events in the seeded corpus")
    row = list(first)
    row[columns.index("who")] = "FORGER"
    placeholders = ", ".join("?" * len(columns))
    with pytest.raises(sqlite3.IntegrityError, match="append-only"):
        loaded.execute(
            f"INSERT OR REPLACE INTO audit_event ({_quoted(columns)}) VALUES ({placeholders})", row
        )
