/**
 * The unit engine's answers, recorded (OF-BLD-012 §5.3).
 *
 * `src/engine/units.ts` is the reference implementation and
 * `core/openferment_core/units.py` is its mirror, working from the same table.
 * Two implementations of one algorithm drift the first time somebody fixes a
 * bug in one of them, so the TypeScript side's answers to a fixed set of
 * inputs are written down here and the Python test asserts equality on every
 * one. Nothing in this file is a hand-typed expected value: each case is what
 * `units.ts` actually returned at export time. If the two sides disagree, this
 * side is right — that is the whole arrangement.
 *
 * THE CASES ARE CHOSEN TO BE AWKWARD. Aliases that differ only by case ('mM' is
 * millimolar, 'mm' is millimetres), affine temperature, the superscript-blind
 * fallback, middot separators, an unknown unit, an empty unit, and the refusals
 * that carry a reason. Twenty easy cases would prove less than these.
 *
 * Emits core/tests/fixtures/units.json. Regenerated by `pnpm test:core` so the
 * fixture never lags the engine, and gitignored for the same reason
 * corpus.json is: a committed copy would be a second source that drifts.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import {
  convert,
  explainRefusal,
  normalizeUnit,
  quantityEquals,
  toSI,
  unitFamily,
} from '../src/engine/units';

const OUT = 'core/tests/fixtures/units.json';

// ── normalise: raw notation → table key, and its family ────────────────
const NORMALIZE_INPUTS = [
  'g/L', // the commonest alias
  'mg L-1', // ASCII superscript, matched by the fallback
  'mg·L⁻¹', // middot separator (the §5.3 example)
  'mg⋅L⁻¹', // dot operator, the other middot
  'µg/mL',
  'ug/ml', // ASCII micro, lower-case alias
  '1/h',
  'per day',
  'degC',
  'K', // in the table directly
  'k', // lower-case alias to the same
  '% dw',
  '%TSP', // no space — needed an alias
  'mM', // millimolar via lower-case alias …
  'mm', // … but 'mm' is in the table as millimetres
  'M', // molar via the alias …
  'm', // … and 'm' is the metre
  'G L-1', // wrong case, superscript-blind fallback
  'kg/m3',
  'g/L/h',
  'µmol/m²/s',
  '', // pH — the empty unit is a real key
  'furlongs', // unknown
  '  g/L  ', // whitespace
];

const normalize = NORMALIZE_INPUTS.map((raw) => ({
  raw,
  unit: normalizeUnit(raw),
  family: unitFamily(raw),
}));

// ── convert: value, from, to → result (or the error class) ─────────────
const CONVERT_INPUTS: [number, string, string][] = [
  [2.5, 'mg/L', 'g L⁻¹'],
  [37, '°C', 'K'],
  [98.6, '°F', '°C'],
  [300, 'K', '°C'],
  [1, 'd⁻¹', 'h⁻¹'],
  [24, 'g L⁻¹ d⁻¹', 'g L⁻¹ h⁻¹'],
  [5, 'g/g/h', 'mg g⁻¹ h⁻¹'],
  [100, 'mg/dL', 'g L⁻¹'],
  [1, 'kg m⁻³', 'g L⁻¹'],
  [3.6, 'MJ kg⁻¹', 'kWh kg⁻¹'],
  [1, 'g/L', 'h⁻¹'], // incompatible — must throw
  [1, 'g/L', 'furlongs'], // unknown — must throw
];

const conversions = CONVERT_INPUTS.map(([value, from, to]) => {
  try {
    return { value, from, to, result: convert(value, from, to), error: null };
  } catch (e) {
    return { value, from, to, result: null, error: (e as Error).message };
  }
});

// ── toSI: the family's designated display twin ─────────────────────────
const SI_INPUTS: [number, string][] = [
  [1, 'g L⁻¹'],
  [300, 'K'],
  [2, 'mg/g'],
  [5, 'unknownunit'], // passes through untouched
];
const si = SI_INPUTS.map(([value, unit]) => ({ value, unit, si: toSI(value, unit) }));

// ── refusals: the conversions that come with a reason ──────────────────
const REFUSAL_INPUTS: [string, string][] = [
  ['% TSP', 'g/L'],
  ['g/L', '% TSP'], // symmetric
  ['EUR kg⁻¹', 'USD kg⁻¹'],
  ['% TSP', '% DW'],
  ['g/L', 'h⁻¹'], // incompatible but no recorded trap → null
  ['g/L', 'mg/L'], // same family → null
  ['furlongs', 'g/L'], // unknown → null
];
const refusals = REFUSAL_INPUTS.map(([from, to]) => ({ from, to, because: explainRefusal(from, to) }));

// ── quantityEquals: the tolerance rule §6.2 reuses ─────────────────────
const EQUALS_INPUTS: [{ value: number; unit: string }, { value: number; unit: string }, number][] = [
  [{ value: 4.2, unit: 'g/L' }, { value: 4200, unit: 'mg/L' }, 2],
  [{ value: 4.2, unit: 'g/L' }, { value: 4.28, unit: 'g/L' }, 2], // 1.9 % — inside
  [{ value: 4.2, unit: 'g/L' }, { value: 4.3, unit: 'g/L' }, 2], // 2.3 % — outside
  [{ value: 4.2, unit: 'g/L' }, { value: 42, unit: 'g/L' }, 2],
  [{ value: 1, unit: '% TSP' }, { value: 1, unit: 'g/L' }, 2], // families differ
  [{ value: 0, unit: 'g/L' }, { value: 0, unit: 'mg/L' }, 2], // zero against zero
  [{ value: 4.2, unit: 'g/L' }, { value: 4.22, unit: 'g/L' }, 0.5], // §2.4's tighter tolerance
];
const equals = EQUALS_INPUTS.map(([a, b, tolerancePct]) => ({
  a,
  b,
  tolerancePct,
  result: quantityEquals(a, b, tolerancePct),
}));

const fixture = {
  generatedBy: 'scripts/export-unit-fixtures.ts — do not edit; regenerate with pnpm export:unit-fixtures',
  normalize,
  conversions,
  si,
  refusals,
  equals,
};

mkdirSync('core/tests/fixtures', { recursive: true });
writeFileSync(OUT, JSON.stringify(fixture, null, 2) + '\n');

const pairs = normalize.length + conversions.length + si.length + refusals.length + equals.length;
console.log('\nopenFerment unit fixtures');
console.log('─────────────────────────');
console.log(`  normalize    ${normalize.length} (${normalize.filter((n) => n.unit === null).length} unknown)`);
console.log(`  conversions  ${conversions.length} (${conversions.filter((c) => c.error).length} refused)`);
console.log(`  toSI         ${si.length}`);
console.log(`  refusals     ${refusals.length} (${refusals.filter((r) => r.because).length} carry a reason)`);
console.log(`  equals       ${equals.length}`);
console.log(`  pairs        ${pairs} recorded from the TypeScript engine`);
console.log(`\n✓ ${OUT}`);
