"""The canonical openFerment entity schema.

Ported from `src/data/types.ts`, which is now generated back out of these models
rather than hand-written. Split by concern, one module per group of types that
change together.

Two modules are not in the original migration brief's list — `ledger` and
`design`. The brief was enumerating an earlier `types.ts` and those concerns had
grown since. Omitting them would have generated a TypeScript file missing types
the application imports, so they are here, in their own modules rather than
squeezed into a neighbouring one.

Two types in `econ` are deliberately NOT modelled: `CostModel` carries a
function and `ResultGrid` carries `Float64Array`. Neither is a data shape and
neither survives a round trip through JSON Schema; they stay hand-written in
TypeScript, and `econ.py` explains why at the point where the reader will look
for them.
"""

from __future__ import annotations

from .bio import Strain
from .corpus import (
    CorpusThread,
    CoverageDispute,
    EvidenceClass,
    IngestStage,
    IngestStatus,
    Paper,
    PaperSection,
    Provenance,
    SourceType,
)
from .design import (
    ClaimBound,
    ClaimScope,
    DesignRecord,
    EmbargoStatus,
    MSPDistribution,
    Patent,
    PublicationStatus,
    ScopeHit,
    SensitivityEntry,
    Tier,
    TierResult,
    TierState,
    TierValue,
)
from .econ import (
    AssumptionBasis,
    BasisModel,
    BasisRecord,
    BasisUnsourced,
    CostLine,
    GridPointResult,
    Scenario,
    ScenarioAssumption,
    ScenarioDim,
    SensitivityRow,
)
from .learn import (
    CheckpointQuestion,
    Collection,
    EmbedBlock,
    EmbedKind,
    LearnModule,
    Lesson,
    LessonBlock,
    NumericAnswer,
    ProseBlock,
)
from .ledger import (
    Aggregate,
    AggregateStratum,
    ConsistentStatus,
    ConstraintCheck,
    ContradictedStatus,
    Contradiction,
    ContradictionKind,
    ContradictionStatus,
    DetectedBy,
    ExcludedRecord,
    ParameterView,
    RefereeStatus,
    UncheckedStatus,
)
from .ontology import (
    AnalysisMethod,
    FieldId,
    NumberingConvention,
    ParameterDef,
    ParameterFamily,
    RefuseConversion,
)
from .protocol import (
    BaseBatch,
    DecisiveMeasurement,
    Deviation,
    EstimatedMinutes,
    Material,
    Protocol,
    ProtocolCategory,
    ProtocolReference,
    ProtocolVersion,
    ResultField,
    RunOutcome,
    RunState,
    ScalingClass,
    Step,
    StockSolution,
    TimerState,
)
from .records import (
    AuditEvent,
    CorrectedValue,
    CuratorNote,
    ExtractionRecord,
    ExtractorRun,
    FalsePositive,
    GoldValue,
    RecordStatus,
    RunOutcomeKind,
    RunOutput,
    RunResult,
    SIValue,
    ValueRange,
)
from .session import (
    ActivityEvent,
    AnswerMessage,
    ChatFlow,
    ChatMessage,
    ChatRetrievalHit,
    ChatSession,
    ChatToolCall,
    ClarifyMessage,
    ClarifyOption,
    ClarifyPrompt,
    Job,
    JobKind,
    JobStage,
    JobStatus,
    PlanMessage,
    SessionScope,
    SystemMessage,
    ToolMessage,
    UserMessage,
)

__all__ = [
    "ActivityEvent",
    "Aggregate",
    "AggregateStratum",
    "AnalysisMethod",
    "AnswerMessage",
    "AssumptionBasis",
    "AuditEvent",
    "BaseBatch",
    "BasisModel",
    "BasisRecord",
    "BasisUnsourced",
    "ChatFlow",
    "ChatMessage",
    "ChatRetrievalHit",
    "ChatSession",
    "ChatToolCall",
    "CheckpointQuestion",
    "ClaimBound",
    "ClaimScope",
    "ClarifyMessage",
    "ClarifyOption",
    "ClarifyPrompt",
    "Collection",
    "ConsistentStatus",
    "ConstraintCheck",
    "ContradictedStatus",
    "Contradiction",
    "ContradictionKind",
    "ContradictionStatus",
    "CorpusThread",
    "CorrectedValue",
    "CostLine",
    "CoverageDispute",
    "CuratorNote",
    "DecisiveMeasurement",
    "DesignRecord",
    "DetectedBy",
    "Deviation",
    "EmbargoStatus",
    "EmbedBlock",
    "EmbedKind",
    "EstimatedMinutes",
    "EvidenceClass",
    "ExcludedRecord",
    "ExtractionRecord",
    "ExtractorRun",
    "FalsePositive",
    "FieldId",
    "GoldValue",
    "GridPointResult",
    "IngestStage",
    "IngestStatus",
    "Job",
    "JobKind",
    "JobStage",
    "JobStatus",
    "LearnModule",
    "Lesson",
    "LessonBlock",
    "MSPDistribution",
    "Material",
    "NumberingConvention",
    "NumericAnswer",
    "Paper",
    "PaperSection",
    "ParameterDef",
    "ParameterFamily",
    "ParameterView",
    "Patent",
    "PlanMessage",
    "ProseBlock",
    "Protocol",
    "ProtocolCategory",
    "ProtocolReference",
    "ProtocolVersion",
    "Provenance",
    "PublicationStatus",
    "RecordStatus",
    "RefereeStatus",
    "RefuseConversion",
    "ResultField",
    "RunOutcome",
    "RunOutcomeKind",
    "RunOutput",
    "RunResult",
    "RunState",
    "SIValue",
    "ScalingClass",
    "Scenario",
    "ScenarioAssumption",
    "ScenarioDim",
    "ScopeHit",
    "SensitivityEntry",
    "SensitivityRow",
    "SessionScope",
    "SourceType",
    "Step",
    "StockSolution",
    "Strain",
    "SystemMessage",
    "Tier",
    "TierResult",
    "TierState",
    "TierValue",
    "TimerState",
    "ToolMessage",
    "UncheckedStatus",
    "UserMessage",
    "ValueRange",
]
